const ESSAYS = [
{
    title: "Blinded By the Law: Jewish Legalism and Perspectives on Salvation in the Gospels",
    desc: "Argues from the Gospels that the Jews at the time of Christ were largely legalistic, trusting in law-keeping and Abrahamic descent for salvation, while highlighting the faithful remnant — like the disciples and the man born blind — who instead looked in faith for the Messiah.",
    year: "December 4, 2025",
    content: `
      <div class="toc">
        <div class="toc-title">Contents</div>
        <ol>
            <li><a href="#introduction">Introduction</a></li>
            <li><a href="#responses-to-john-the-baptist">Responses to John the Baptist</a></li>
            <li><a href="#matthew-12113">Matthew 12:1–13</a></li>
            <li><a href="#john-5">John 5</a></li>
            <li><a href="#john-89">John 8–9</a></li>
            <li><a href="#luke-18914">Luke 18:9–14</a></li>
            <li><a href="#matthew-23">Matthew 23</a></li>
            <li><a href="#conclusion">Conclusion</a></li>
        </ol>
      </div>

      <article>
        <h2 id="introduction">Introduction</h2>
        <p>Jesus was largely rejected by His own people[cite: 8]. John makes this shocking statement about Jesus in his gospel prologue: "He came to His own, and those who were His own did not receive Him" (John 1:11)[cite: 8]. The overall denial of Christ by the Jews has caused many to wrestle with the reason for this rejection[cite: 8]. It is thus important to understand what the Jews believed about salvation at the time of Christ[cite: 8]. Traditionally, the Jewish leaders, followed by their people, have been viewed as legalists, although recent scholars have challenged this perspective[cite: 8]. This paper will prove from the Gospel accounts that the Jews at the time of Christ were largely legalistic and relied on the works of the law and their Abrahamic descent to receive eternal life and be counted righteous before God[cite: 8]. It will also explore key exceptions to this characterization and highlight the expectation of and faith in a Messiah that is commended by Jesus and the Gospel writers[cite: 8]. The Gospels present the majority of Jews at the time of Christ as legalistic, believing their obedience and lineage granted them some form of salvation[cite: 8].</p>
        <p>The characterization of second-temple Judaism as legalistic has been questioned in recent decades by the loosely defined "New Perspective on Paul" (NPP) movement.<sup id="fnref1"><a href="#fn1">1</a></sup>[cite: 8] While this paper is not an evaluation of the NPP or Paul's writings, the presuppositions and beliefs of the NPP are challenged by what the Gospels reveal about Jewish beliefs on salvation[cite: 8]. The NPP advocates that the Jews were actually not legalistic but rather held to covenantal nomism.<sup id="fnref2"><a href="#fn2">2</a></sup>[cite: 8] Thus, the Jewish people largely believed they entered God's gracious covenant through Abrahamic lineage and remained in the covenant by obedience[cite: 8]. N. T. Wright summarizes, "the Jew keeps the law out of gratitude, as the proper response to grace - not, in other words, in order to get into the covenant people, but to stay in."<sup id="fnref3"><a href="#fn3">3</a></sup>[cite: 8] According to Wright and others, what Paul and the NT authors are rebuking among the Jews is their exclusion of others from God's grace on the grounds of Abrahamic descent[cite: 8]. Thus, the problem among the Jews at the time of Christ was not legalism, but an ethnocentrist or ethnoexclusivist attitude.<sup id="fnref4"><a href="#fn4">4</a></sup>[cite: 8] While the NPP may do well in emphasizing the ethnocentrism of the Jewish people, it falls short in its dismissal of legalism.<sup id="fnref5"><a href="#fn5">5</a></sup>[cite: 8] A study of the Gospels themselves clearly demonstrates the legalism and ethnocentrism of second-temple Judaism[cite: 8]. The Jews were in fact legalists and their rampant legalism, combined with ethnocentrism, directly led to their rejection of the Messiah[cite: 8]. The legalistic tendencies and prevailing views of salvation among the Jews become evident in their responses to John the Baptist and in five key passages: Matthew 12:1-13; John 5; John 8-9; Luke 18:9-14; and Matthew 23[cite: 8].</p>

        <h2 id="responses-to-john-the-baptist">Responses to John the Baptist</h2>
        <p>The Gospels first demonstrate Jewish perspectives on salvation through the responses to John the Baptist[cite: 8]. The positive response of some of the Jewish people and negative response by the religious leaders sets the stage for Christ's interactions with them[cite: 8]. Each Gospel emphasizes the ministry of John the Baptist, which is to prepare the way of the Lord, as stated in Isaiah 40:3[cite: 8]. John prepares the way of the Lord by his preaching and baptism, which converge as he reveals who the Christ is[cite: 8]. John's message to the Jewish people is clear: "Repent, for the kingdom of heaven is at hand" (Matt 3:2)[cite: 8]. His ministry is summarized by Mark and Luke as "preaching a baptism of repentance for the forgiveness of sins" (Mark 1:4; Luke 3:3)[cite: 8]. Many Jews respond to John's message as his ministry was marked by the residents of Judea and the Jordan region "being baptized by him in the Jordan river, while confessing their sins" (Matt 3:6)[cite: 8]. These Jewish people responded to John's call to repent by acknowledging their sinfulness[cite: 8]. Matthew distinguishes these repentant crowds from the next group: "many of the Pharisees and Sadducees coming to his baptism" (3:7)[cite: 8]. Matthew presents John's interaction with these leaders to highlight their rejection of salvation and foreshadow Christ's later condemnation of them[cite: 8].</p>
        <p>The Pharisees and Sadducees are introduced here for the first time in Matthew's gospel and characterized by John as a "brood of vipers" (Matt 3:7).<sup id="fnref6"><a href="#fn6">6</a></sup>[cite: 8] They do not come to be baptized by John and do not demonstrate the repentant posture found in the recipients of his baptism.<sup id="fnref7"><a href="#fn7">7</a></sup>[cite: 8] While the crowds confess their sins and are baptized for repentance, John questions why the Pharisees and Sadducees come, asking "You brood of vipers, who warned you to flee from the wrath to come?" (3:7)[cite: 8]. John's sarcastic question demonstrates they do not in fact come to him to be baptized and escape from the coming wrath[cite: 8]. The religious leaders believe they can say to themselves, "We have Abraham for our father" (3:9)[cite: 8]. John warns there is no escape from the judgment through this ethnocentrism, and that if they do not "bear fruit in keeping with repentance" they will be cut down and thrown into the fire (3:8, 10)[cite: 8]. He says the one coming after him will baptize with fire by threshing the wheat and burning up the chaff (3:11-12)[cite: 8]. John's message, "Repent for the kingdom of heaven is at hand" (3:2), prepares the way for the Lord by urging the Jews to repent before the coming judgment[cite: 8]. The baptism of repentance offered by John will give way to the Messiah who baptizes with the Spirit and with fire[cite: 8]. Matthew records no response by the Pharisees and Sadducees in this narrative, only the words John voices on their behalf, "We have Abraham as our father" (3:9)[cite: 8]. The leaders are presented with the options: bear the fruit of repentance or cling to their Abrahamic lineage and continue in their current deeds[cite: 8].</p>
        <p>John's preparation of the Lord's way climaxes in Christ's baptism[cite: 8]. Priests and Levites from Jerusalem asked John whether he was the Messiah, Elijah, or the prophet to come (John 1:19-21)[cite: 8]. When John saw Jesus coming to be baptized, he proclaimed, "Behold, the Lamb of God who takes away the sin of the world" (1:29)[cite: 8]. John pointed those who confessed their sin while being baptized, to the Lamb who could take away their sin[cite: 8]. He baptized Jesus and saw the Spirit descend as a dove, demonstrating that Jesus is the one who baptizes with the Spirit, and is truly the Son of God (1:30-34)[cite: 8]. Yet the religious leaders do not follow Jesus as the Messiah[cite: 8]. Instead, it is those who will become His disciples that follow John's direction to behold the Lamb[cite: 8]. First, Andrew exclaims, "We have found the Messiah" (1:41), demonstrating the Jewish Messianic expectation[cite: 8]. Philip expands this confession, "We have found Him of whom Moses in the Law and the prophets wrote: Jesus of Nazareth, the son of Joseph" (1:45)[cite: 8]. The disciples immediately heed the direction of John and their companions to follow Jesus because they have been waiting for the Messiah[cite: 8].</p>
        <p>The responses to John the Baptist are foundational for understanding Christ's interactions with the Jews[cite: 8]. Many confessed their sins and others, like the disciples, even followed Jesus after John pointed the way[cite: 8]. The Pharisees and Sadducees were rebuked by John as a brood of vipers who need to repent[cite: 8]. After John reveals that Jesus is the Christ, they continue in their sins instead of submitting to Him[cite: 8]. The religious teachers should have urged their people, like John did, to follow Christ[cite: 8]. Instead, out of the hardness of their hearts, they continued in their empty religious works and did not bear the fruit of repentance[cite: 8]. As Jesus demonstrates that He is the Messiah by teaching and healing, He rebukes the religious leaders for their legalistic hypocrisy[cite: 8].</p>

        <h2 id="matthew-12113">Matthew 12:1–13</h2>
        <p>In Matthew 12:1-13, the disciples eat heads of grain and Jesus heals a man's hand on the Sabbath day[cite: 8]. The Pharisees rebuke Jesus for the action of His disciples and test Him by asking whether it is lawful to heal on the Sabbath[cite: 8]. These related Sabbath pericopes demonstrate the Pharisees' legalism[cite: 8]. Christ's corresponding rebukes shows how His followers should prudently apply the law[cite: 8].</p>
        <p>The disciples violate Jewish interpretation of the Sabbath law in Matthew 12:1-8[cite: 8]. They picked and ate grain out of hunger (v. 1), and the Pharisees point out that these actions are unlawful (ἔξεστιν) on the Sabbath (v. 2; cf. v. 10)[cite: 8]. The Old Testament added a few stipulations to the original Sabbath command, but the rabbis fleshed out this command even further, including thirty-nine different categories of prohibited work.<sup id="fnref8"><a href="#fn8">8</a></sup>[cite: 8] Jesus cites two narratives in Scripture: David and his men, and the temple priests (vv. 3-5)[cite: 8]. David and his men ate on the Sabbath from hunger, and the priests work on the Sabbath because of the importance of temple worship[cite: 8]. David and his hungry warriors show that human needs should not be neglected on the Sabbath[cite: 8]. The reference to priests working on the Sabbath in verse 5 implies that Christ's disciples, by following Jesus, are serving God like the priests do[cite: 8]. In fact, Jesus and His kingdom are even greater than the temple (v. 6)[cite: 8]. The scene concludes with Jesus rebuking the Pharisees for their lack of compassion and declaring Himself Lord of the Sabbath (vv. 7-8)[cite: 8]. This legalistic lack of compassion is shown again in the following Sabbath narrative[cite: 8].</p>
        <p>Jesus and his disciples next encounter the Pharisees in their synagogue[cite: 8]. Seeing a man with a paralyzed hand, the Pharisees see the opportunity to accuse Jesus, as Matthew editorially notes (Matt 12:10)[cite: 8]. They do not question Christ's ability to heal but ask if it is lawful (ἔξεστιν; cf. v. 2) to heal on the Sabbath[cite: 8]. Jewish literature shows the Pharisees thought it was unlawful to heal on the Sabbath unless it was a life-or-death matter.<sup id="fnref9"><a href="#fn9">9</a></sup>[cite: 8] The Pharisees are entirely focused on the law and this apparent opportunity to bring legal charges against Jesus[cite: 8]. In response, Jesus does not argue over the Mosaic law, Rabbinic traditions, or the definition of work[cite: 8]. He simply asks the rhetorical question: if any of you had a sheep fall into a pit on the Sabbath, would he not lift it out? (12:11-12)[cite: 8]. Lifting a sheep out of a pit is work, a good deed, which even the Pharisees would not balk at[cite: 8]. Yet, as Jesus declares, "How much more valuable is a man than a sheep?" (v. 12)[cite: 8]. Jesus then heals the man, and the Pharisees depart to plot a way to destroy Jesus (vv. 12-14)[cite: 8]. The conclusion of these two Sabbath events is stated by Jesus, "So then it is lawful to do good on the Sabbath" (v. 12)[cite: 8].</p>
        <p>The Pharisees in Matthew 12 condemn the disciples for satiating their hunger and seek to accuse Jesus of healing a man on the Sabbath[cite: 8]. By so doing, they display a complete lack of compassion (Matt 12:6) and focus on external observance of the law instead of the love the law requires[cite: 8]. Christ's rebuke of the Pharisees from Hosea 6:6, "I desire compassion and not a sacrifice" (Matt 12:7) shows the danger of legalism[cite: 8]. The Pharisees were so focused on the letter of the law that they neglected the compassion required by it[cite: 8]. As Charles Quarles comments on the quotation of Hosea, "Though the Pharisees sought the mercy of God through acts of sacrifice, they failed to show mercy to other sinners."<sup id="fnref10"><a href="#fn10">10</a></sup>[cite: 8] They were like a slave who had been forgiven a great debt but refused to forgive his own debtors (Matt 18:21-35)[cite: 8]. In their legalism, they miss the point of the Sabbath and show no love towards the disciples, or to the man in their synagogue—using him as a legal pawn[cite: 8]. Instead of legalism, Jesus teaches, as Steven Stiles puts it, "the Sabbath is to be kept holy, but this does not exclude doing good, especially showing mercy to those in need...his main purpose is to declare what should be done on the Sabbath, namely, good."<sup id="fnref11"><a href="#fn11">11</a></sup>[cite: 8] The legalism of the Pharisees causes them to miss showing mercy as required by the law[cite: 8]. It blinds them to real need and causes them to reject Jesus, the one who keeps the law by doing good on the Sabbath[cite: 8]. In Matthew 12:1-13, the Pharisees reject their Messiah in favor of their legal system[cite: 8]. Their legalism manifests itself again in John 5, where their perspective on salvation is made even clearer[cite: 8].</p>

        <h2 id="john-5">John 5</h2>
        <p>John chapter five opens with Jesus healing a man who was a paralytic for thirty-eight years, once again, on the Sabbath (John 5:1-9)[cite: 8]. The Jews scold him for carrying his mat on the Sabbath, to which he replies that the man who healed him gave him this command (5:10-13)[cite: 8]. John notes that after this event, "the Jews began persecuting Jesus because he was doing these things on the Sabbath" (5:16)[cite: 8]. Jesus responds to this persecution, not by asserting again that He showed mercy, as in Matthew 12:9-13, but with, "My Father is working until now and I Myself am working" (5:17)[cite: 8]. Jesus says He can heal on the Sabbath because His Father is working on the Sabbath[cite: 8]. The Jews recognize that Jesus is making Himself equal with God and respond by renewing their persecution (5:17-18)[cite: 8]. As Kang writes of the Jews, "In their blind zeal for their Law, they failed to see the divine power of Jesus."<sup id="fnref12"><a href="#fn12">12</a></sup>[cite: 8] They reject Jesus because of their legalistic approach to the Sabbath law and thus reject His claim to be equal with God (cf. 9:24)[cite: 8]. Jesus responds by asserting that John the Baptist, His works, and His Father all testify about Him (5:33-47)[cite: 8]. The Jews, who claim to have God as their father, have not heard His testimony (5:37)[cite: 8]. In fact, although they claim to love the law, Jesus says to them, "you do not have His word abiding in you, because you do not believe the one whom He sent" (5:38)[cite: 8]. The Jews "search the Scriptures" thinking in them they have "eternal life," but miss the One the Scriptures testify about and are unwilling to come to Him for eternal life (5:39-40)[cite: 8].</p>
        <p>The Jews were blinded to the coming of Jesus for their salvation by their legalism[cite: 8]. They searched the Scriptures diligently, thinking to find eternal life in them[cite: 8]. D. A. Carson characterizes the searching Jews as hoping for "final acceptance by God" in the form of eternal life.<sup id="fnref13"><a href="#fn13">13</a></sup>[cite: 8] This is seen most clearly in the Mishnah: "The more Torah, the more life... he who has acquired for himself words of Torah has acquired for himself life in the world to come."<sup id="fnref14"><a href="#fn14">14</a></sup>[cite: 8] The words of Christ and the very words of the Jews themselves in the Mishnah demonstrate their belief about salvation[cite: 8]. As Colin Kruse puts it, "Through the diligent study of the Scriptures the Jewish leaders believed they would find eternal life."<sup id="fnref15"><a href="#fn15">15</a></sup>[cite: 8] Yet these Jews who diligently searched the Scriptures do not have God's word abiding in them because they do not believe in Christ (John 5:38)[cite: 8]. They reject Christ who came in the name of His Father (5:43)[cite: 8]. By disbelieving Jesus, they disbelieve Moses who wrote the words they claim to uphold, as Jesus says, "If you believed Moses, you would believe Me, for he wrote about Me" (5:46)[cite: 8]. Thus, He says, "the one who accuses you is Moses, in whom you have set your hope" (5:45)[cite: 8]. The Jews sought to accuse (κατηγορήσωσιν) Christ in Matthew's Sabbath-day account (Matt 12:10) but are being accused (κατηγορῶν) by Moses for their rejection of Christ (John 5:45)[cite: 8]. The Jews condemn themselves by disbelieving the words they study, and the one whom the words spoke of[cite: 8].</p>
        <p>The Jews sought life in the study of Scripture and tradition[cite: 8]. They rejected the one whom the Scriptures testified about and looked forward to[cite: 8]. Their search for life led them to legalism, believing that their external obedience had them on the path to life and that they had no need to repent[cite: 8]. They rejected Christ, the one who has life in Himself; those who were Christ's own people did not receive Him (John 1:4, 11)[cite: 8]. Their legalism led to their rejection of Christ[cite: 8]. However, as noted in the introduction and seen in the responses to John the Baptist, the Jews also rejected Christ and remained in their sin because of their ethnocentrism[cite: 8]. They believed they had no need of salvation, of freedom from slavery, because they were descended from Abraham[cite: 8]. This theme is continued in John 8-9[cite: 8].</p>

        <h2 id="john-89">John 8–9</h2>
        <p>In John 8:12-9:41, Jesus teaches that He is the light of the world and immediately proves His teaching by healing a man born blind[cite: 8]. This is set in the larger context of the feast of booths (John 7:2) during which Jesus demonstrates that He is the Lord who brought Israel out of Egypt (8:24, 28, 58), the rock of living water (7:37-39), and guiding light (8:12; 9:5)[cite: 8]. He is thus "the fulfillment of the Feast of Tabernacles," namely, the one who led Israel out of slavery in the exodus and will lead His people in a new exodus.<sup id="fnref16"><a href="#fn16">16</a></sup>[cite: 8] His foundational statement, "I am the Light of the world, he who follows Me will never walk in the darkness but will have the Light of life," is immediately rejected by the Pharisees (8:12-13)[cite: 8]. Jesus again emphasizes, as He did in chapter five, that His Father testifies about Him, and these Pharisees do not actually know the Father (8:18-19)[cite: 8]. He calls the crowds to believe in Him lest they die in their sins, and many do appear to believe in Him (8:24-30)[cite: 8]. However, this is not a belief like that manifested by the recipients of John's baptism or the disciples in Matthew 3 and John 1[cite: 8].</p>
        <p>Christ calls the supposedly believing Jews to abide in His word in order to be true disciples and to be set free by the truth[cite: 8]. The Jews respond, "We are Abraham's seed and have never been enslaved to anyone. How is it that You say, 'You will become free'?" (8:33)[cite: 8]. Christ tells them that sinners are slaves of sin, they can be made free by the Son, and that if they were truly Abraham's seed, they would not seek to kill Him (8:34-37)[cite: 8]. They see no need to be baptized and set free but believe they are free because of their Abrahamic descent[cite: 8]. But as John warned the Pharisees and Sadducees, they cannot say to themselves "We have Abraham for our father" (Matt 3:9)[cite: 8]. When the Jews reaffirm their Abrahamic sonship, Jesus responds, "If you are Abraham's children, you would do the deeds of Abraham" (8:39)[cite: 8]. The deeds of Abraham are related by Jesus in verse 56, "Your father Abraham rejoiced to see My day, and he saw and was glad."[cite: 8] While the Jews tried to claim Abraham as their defense, Edward Clink notes, "It was Jesus to whom Abraham had long been witnessing."<sup id="fnref17"><a href="#fn17">17</a></sup>[cite: 8] The Jews, by their rejection of Christ, show that they are not Abraham's children[cite: 8]. Christ declares "Before Abraham was, I am," claiming the name of Yahweh from Exodus 3, but the Jews respond by picking up stones to throw at Him (8:58-59)[cite: 8]. The children of Abraham reject the Messiah Abraham looked forward to[cite: 8].</p>
        <p>The Jews are blinded to their sin by their Abrahamic descent, believing they do not need to be freed from sin but instead treated as Abraham's and God's children[cite: 8]. John prepared the way for the Messiah by preaching a baptism of repentance, which many Jews did receive while confessing their sins (Matt 3:6-7)[cite: 8]. However, others, like the Pharisees and Sadducees in Matthew 3 and the crowd of Jews in John 8 shut their eyes to the light of the Messiah[cite: 8]. Jesus shows in John 8-9 that He is the light of the world, the Servant to whom the Father spoke: "I will appoint You as a covenant to the people, As a light to the nations, to open blind eyes, to bring out prisoners from the dungeon and those who dwell in darkness from the prison" (Isa 42:6-7)[cite: 8]. These Jews in John 8 believed they were already seeing and set free from prison, when in reality they were enslaved to sin[cite: 8]. Thus, they rejected the Messiah who declared Himself to be the light of the world, the light to the nation[cite: 8]. However, the narrative shifts as Jesus flees the temple, and a truly blind man receives physical and spiritual sight[cite: 8]. In John 9, Jesus proves Himself to be the Servant of whom Isaiah spoke[cite: 8].</p>
        <p>Jesus and His disciples encounter a man blind from birth as they leave the temple[cite: 8]. Jesus reiterates that He is the light of the world (John 9:5) and proves it by healing the man born blind (9:6-7)[cite: 8]. By giving physical sight to a blind man, Jesus shows He can also open the eyes of the spiritually blind[cite: 8]. The now-seeing man testifies that it was Jesus who healed him (9:11), so he is interrogated by the Pharisees (9:13-34)[cite: 8]. Some of the Pharisees dismiss Jesus as one who is not from God, since He healed the man on the Sabbath (9:14, 16)[cite: 8]. Because others disagreed, they questioned the man and his parents further to verify the miracle[cite: 8]. As on previous Sabbath healings, the Pharisees show no care for the person healed.<sup id="fnref18"><a href="#fn18">18</a></sup>[cite: 8] The man is not afraid when the Pharisees interrogate him and dismiss Jesus but simply astounded that he can now see (9:24-34)[cite: 8]. The Pharisees then claim to be disciples of Moses, not Jesus (9:28-29), having not learned their lesson that Moses testified of Jesus (5:39-40)[cite: 8]. The formerly blind man does not care that the Pharisees view Jesus as a sinner, because he can see, and no one has ever healed a man blind from birth (9:25, 30-32)[cite: 8]. He recognizes, "If this man were not from God, He could do nothing" (9:33), so the Pharisees throw him out of the synagogue (9:34)[cite: 8].</p>
        <p>Jesus finds the man again and asks if he believes in the Son of Man (9:35)[cite: 8]. He is eager and willing to believe, asking, "Who is He, Lord, that I may believe in Him?" (9:36)[cite: 8]. This man, like the faithful disciples of John and Jesus, displays a clear expectation of the Messiah[cite: 8]. He is looking (both spiritually and now physically) for the Son of Man[cite: 8]. He does not rely on his Abrahamic lineage or a supposed lack of sin, like the Pharisees[cite: 8]. He does not rest in being a disciple of Moses[cite: 8]. He looks for the coming of the Son of Man, prophesied in Daniel 7:13-14[cite: 8]. Jesus then reveals His identity, and the man responds, "Lord I believe" and worships Jesus (9:38)[cite: 8]. Christ has brought spiritual light and physical light to this man, showing that He is the true light coming into the world (1:9)[cite: 8]. The man has had his physical blindness and spiritual blindness removed by the one who came "so that those who do not see may see and that those who see may become blind" (9:39)[cite: 8]. The Pharisees ask, "we are not blind too, are we?" expecting that Christ will say no[cite: 8]. Instead, Jesus confronts their sin once again, "If you were blind you would have no sin, but since you say, 'We see,' your sin remains" (9:41)[cite: 8]. As Klink comments, "Just like the blind man, before someone can claim 'I believe, they must first declare, 'I am a sinner'."<sup id="fnref19"><a href="#fn19">19</a></sup>[cite: 8] In John 8-9, the Jews believe they are not slaves to sin, but instead children of Abraham and disciples of Moses[cite: 8]. They refuse to believe the Son of Man when He reveals Himself[cite: 8]. Their sin is not forgiven; instead, "it abides precisely because they are so confident of their righteousness."<sup id="fnref20"><a href="#fn20">20</a></sup>[cite: 8] However, as the healed man, along with the faithful recipients of John's baptism and the disciples show, some are waiting for the Messiah and are ready to confess and repent from their sins[cite: 8]. They understand the need for salvation from sin and that only the Messiah can bring resurrection life[cite: 8]. These contrasting perspectives on salvation are also clearly seen in the parable of the Pharisee and the tax collector[cite: 8].</p>

        <h2 id="luke-18914">Luke 18:9–14</h2>
        <p>In the parable of the Pharisee and tax collector, Jesus teaches on the legalism that marked many in the Jewish community at the time of Christ, particularly the religious leaders[cite: 8]. In this same parable He also shows the free confession of sin and calling out to God for salvation that marks His true disciples[cite: 8]. The parable summarizes the view of salvation by those who rejected Christ and the repentant hearts of those who believed in Him[cite: 8].</p>
        <p>Christ addresses this parable "to some people who trusted in themselves that they were righteous and disdained others" (Luke 18:9)[cite: 8]. Self-righteousness is no better exemplified than by the Pharisee in the parable who prays, "God, I thank You that I am not like other people: swindlers, unrighteous, adulterers, or even like this tax collector. I fast twice a week; I pay tithes of all that I get" (18:11-12)[cite: 8]. The characteristic legalism already seen in the gospels is demonstrated here, where it also manifests in pride[cite: 8]. This Pharisee was prideful because he fasted twice a week and paid tithes from everything (cf. Matt 23.23)[cite: 8]. He not only kept God's requirements, but, as Robert Stein notes, "he believed he had done more than God required."<sup id="fnref21"><a href="#fn21">21</a></sup>[cite: 8] The Pharisee believed he earned his righteousness before God by his superb keeping of the law, unlike the tax collector[cite: 8]. This sort of pride leads to disdaining others (18:9)[cite: 8]. John Piper helpfully analyzes, "the exclusivistic treatment of others is one manifestation of the self-righteousness that trusts in its own law-keeping. Legalism and ethnocentrism have the same root. They are not separate conditions of the soul."<sup id="fnref22"><a href="#fn22">22</a></sup>[cite: 8] The legalist in this prayer views himself as superior to others due to his law-keeping[cite: 8]. Legalism, pride, and ethnocentrism are all correlated[cite: 8]. The legalist's prayer is then contrasted with the prayer of the tax collector[cite: 8].</p>
        <p>The tax collector stood apart from the Pharisee and had no regard for his fellow prayer-warriors in the temple[cite: 8]. His humility is demonstrated as he "was not willing to lift up his eyes to heaven but was beating his chest" (Luke 18:13)[cite: 8]. Jesus says the humble will be rewarded with exaltation (18:14)[cite: 8]. What could be more humble than the publican's prayer, "God, be merciful to me, the sinner" (18:13)?[cite: 8] There is no mention of his law-keeping; in fact, he acknowledges that he is a sinner and has broken the law[cite: 8]. He does not look to his fasting or tithe-paying for hope[cite: 8]. He knows he is spiritually blind, lame, and paralyzed[cite: 8]. Like the blind man in John 9, he simply exercises faith in God[cite: 8]. For this reason, Jesus says, "this man went down to his house justified rather than the other" (18:14)[cite: 8].</p>
        <p>Many Jews in the day of Christ, including those He first spoke this parable to (18:9), embodied legalism by trusting in their obedience to the law for righteousness[cite: 8]. The perspective of the Pharisee on salvation in this parable is the same one held by the Jews in John 8-9[cite: 8]. Simply put, their perspective on salvation was that they did not need salvation[cite: 8]. The fault of the Pharisee in Luke 18 was not his actions, but how he viewed them[cite: 8]. F. F. Bruce writes, "His fault lay, not in the performance of these duties, but in his confidence that by their performance he had satisfied God's requirements and might approach Him without any misgivings."<sup id="fnref23"><a href="#fn23">23</a></sup>[cite: 8] Jesus summarizes the religious leaders and the Jews at large in this text, demonstrating that their problem was assuming law-keeping could satisfy God's requirements[cite: 8]. Joel Beeke cites this text in his analysis of the New Perspective on Paul as evidence "that self-righteousness and merit theology were indeed an issue among the Jews."<sup id="fnref24"><a href="#fn24">24</a></sup>[cite: 8] The Pharisee thanks God in his prayer and keeps God's law, at least externally, but he does so in a spirit of boasting[cite: 8]. The law-keeping of the Jewish people was not done out of gratitude to God for saving them, but out of a legalistic and boastful spirit[cite: 8]. Returning to Bruce, "this Pharisee expected the divine approval because he believed he deserved it. The tax collector knew what he deserved; and for that very reason cast himself upon the grace of God."<sup id="fnref25"><a href="#fn25">25</a></sup>[cite: 8] The tax collector is aware of his sin, not claiming to see like the Pharisee praying across from him[cite: 8]. He knows that he is blind and simply cries out to God for mercy[cite: 8]. The tax collector is a remnant among the Jewish community of Christ's day[cite: 8]. He freely confesses his sin before God in stark contrast to the rampant legalism of the religious leaders and the community as a whole[cite: 8]. He is counted by Christ as justified before God, but the Pharisee is condemned[cite: 8]. Christ's condemnation of the legalistic leaders is most clearly seen in Matthew 23[cite: 8].</p>

        <h2 id="matthew-23">Matthew 23</h2>
        <p>Matthew 23 serves as the counterpart to Matthew 5:3-12, insofar as the latter proclaims blessing on the followers of Christ, and the former woe and judgment on those who reject Him[cite: 8]. Jesus addresses both believers and unbelievers in this discourse, as the audience consists of the crowds (representative of the unbelieving world in Matthew's gospel) and His disciples (23:1)[cite: 8]. Thus, while the discourse is primarily about the scribes and Pharisees (23:2), they are not the only hearers[cite: 8]. The hypocrisy and legalism Christ condemns pertains to both the religious leaders and their followers—the larger Jewish community[cite: 8]. Yong-Eui Yang writes, "The only reason that the Pharisees (and other leaders) are so severely criticized by Jesus in Matthew is the fact that they as religious guides not only failed to respond to the teaching and work of Christ and his kingdom, but also misguided other Jews and became a hindrance to them."<sup id="fnref26"><a href="#fn26">26</a></sup>[cite: 8] The specific condemnation of the religious leaders must not cause the reader to overlook the warning and application to the entire religious community, as they readily followed their leaders, a fact seen clearly in the crucifixion account[cite: 8]. Jesus warns against the legalism and hypocrisy displayed in the entire Jewish community, which would lead them to crucify Him later that week[cite: 8].</p>
        <p>The opening verses describe the actions of the scribes and Pharisees (Matt 23:2-12), which is followed by seven declarations of "woe" (23:13-35), followed by a short statement of the coming destruction of the temple (23:36-39)[cite: 8]. Jesus says the scribes and Pharisees have "seated themselves in the chair of Moses," as they teach the Law of Moses to the people (23:2)[cite: 8]. Their teaching should be followed by the people, as Jesus says, "all that they tell you, do and keep" (23:3)[cite: 8]. What should not be imitated is their conduct, "for they speak and do not do" (23:3)[cite: 8]. Their actions are not in accord with God's law, in part, because of their motives: "They do all their deeds to be noticed by men" (23:5)[cite: 8]. Piper writes, "Their pursuit of Torah was not out of gratitude to God, but out of craving for human glory. This is why they could not believe on Jesus."<sup id="fnref27"><a href="#fn27">27</a></sup>[cite: 8] Jesus thus repeats the condemnation Luke recorded in the parable of the Pharisee and the tax collector: "whoever exalts himself shall be humble, and whoever humbles himself shall be exalted" (23:12)[cite: 8]. The legalism manifested by the Jewish leaders led to pride and the judgment announced in the successive verses[cite: 8].</p>
        <p>The first two woes (Matt 23:13, 15) condemn the scribes and Pharisees for leading astray both their local Jewish communities and proselytes[cite: 8]. They "shut off the kingdom of heaven from people; for you do not enter in yourselves nor do you allow those who are entering to go in" (23:13)[cite: 8]. The religious leaders throughout the gospels refuse to confess their sin, instead preaching obedience to a law that they themselves neglect (23:23)[cite: 8]. They refused to confess their sins and confess Jesus as the Messiah and sought to prevent others from doing so (cf. John 9:22-34)[cite: 8]. The third woe, concerning oaths, demonstrates how the leaders manipulated the law to avoid its penalty through external obedience (23:17-22)[cite: 8]. The fourth and central woe is the clearest description of legalism in the oracle: "Woe to you, scribes and Pharisees, hypocrites! For you tithe mint and dill and cumin and have neglected the weightier provisions of the Law: justice and mercy and faithfulness; but these are the things you should have done without neglecting the others. You blind guides, who strain out a gnat but swallow a camel" (23:23-24)[cite: 8].</p>
        <p>The religious leaders obeyed the law externally, but not internally[cite: 8]. As C. J. Williams writes, "they got the details right in some respects, but details were all they had."<sup id="fnref28"><a href="#fn28">28</a></sup>[cite: 8] As shown in their condemnation of the disciples and heartless treatment of the disabled (Matt 12:1-13), the leaders lacked the justice, mercy, and faithfulness required by the law[cite: 8]. Jesus summarized the proper attitude toward neighbor in the Sermon on the Mount, "in all things, whatever you want people to do for you, so do for them, for this is the law and the prophets" (Matt 7:12)[cite: 8]. The Jewish people, following their leaders, strained out gnats such as washing hands or refraining from journeys, but gulped down camels of pride, injustice, and overall unmerciful behavior[cite: 8]. Their legalism led to blatant hypocrisy[cite: 8].</p>
        <p>Woes five and six condemn the lack of repentance manifested by the religious leaders[cite: 8]. Their external obedience is like failing to wash the inside of a cup or like painting the outside of a tomb (Matt 23:25-28)[cite: 8]. The ones who claim to love the law are in fact, "full of hypocrisy and lawlessness" (23:28)[cite: 8]. The seventh woe condemns them for building tombs for their prophets and saying, "If we had been living in the days of our fathers, we would not have been partners with them in shedding the blood of the prophets" (Matt 23:30)[cite: 8]. Rather than being sons of Abraham, as the Jews in John 8 claimed, they are by descent and action, "sons of those who murdered the prophets" (23:31)[cite: 8]. Had they truly listened to Moses and the prophets, they would recognize that Jesus is the Messiah, but blinded by their sin, they will fill up the measure of their fathers by crucifying him (23:32)[cite: 8]. Jesus then pronounces the same judgment that John the Baptist spoke, "You serpents, you brood of vipers, how will you escape the sentence of hell?" (23:33; cf. 3:7)[cite: 8]. They will not escape the one who baptizes by fire[cite: 8]. By condemning Jesus to death, they condemn themselves and will slither like snakes to escape the fire they lit[cite: 8]. This fiery judgment is described by Jesus in two stages in Matthew 23:36-25:46[cite: 8]. The coming destruction of Jerusalem in A.D. 70 serves as a sign and seal of the final eschatological judgment[cite: 8]. The legalism and hypocrisy of the religious leaders will bring about God's judgment[cite: 8]. In this discourse, as Quarles puts it, "Jesus recognizes that the Pharisees and their scribes are wicked shepherds and those who follow them do so at the peril of their own souls."<sup id="fnref29"><a href="#fn29">29</a></sup>[cite: 8] The discourse of Matthew 23 is a condemnation on the leaders and by extension a warning to cease following them in their legalism and turn to Christ[cite: 8].</p>

        <h2 id="conclusion">Conclusion</h2>
        <p>The Jewish community at the time of Christ was legalistic to the point of rejecting their own Messiah[cite: 8]. The Pharisees, Sadducees, and other religious leaders are characterized in the gospels as focused on external obedience to the law, but missing the heart of the law[cite: 8]. Their rejection of John and his baptism led to their rejection of Christ[cite: 8]. They did not confess their sins or turn to Christ for salvation; instead, they "trusted in themselves that they were righteous and disdained others" (Luke 18:9)[cite: 8]. Instead of keeping the law out of gratitude as advocates of the NPP have posited, they prided themselves on their works and excluded others in contempt[cite: 8]. The Jewish community largely followed their various leaders in this embrace of legalism and refusal to believe in the Messiah[cite: 8]. However, there were exceptions to this rule, beginning right away with the recipients of John's baptism[cite: 8]. At the time of Christ many were ready to receive John's message: repent and follow the Lamb of God[cite: 8]. The disciples and the blind man examined in this paper embody the response of the parabolic tax collector, crying out "God, be merciful to me, the sinner" (Luke 18:13)[cite: 8]. The disciples and the blind man were disdained by the majority of the Jewish community, who neglected the love commanded in the law[cite: 8]. Yet they were not rejected by Jesus[cite: 8]. This remnant among the Jews demonstrates that God graciously saves all who believe, even out of a nation that crucified Him[cite: 8]. The life of Christ, even the rejection of Him by the legalistic Jews, was recorded, "so that you may believe that Jesus is the Christ, the Son of God; and that believing you may have life in His name" (John 20:31)[cite: 8]. God continues to save His remnant through their faith in Christ[cite: 8].</p>
      </article>

      <div class="footnotes">
        <h2>Notes</h2>
        <ol>
          <li id="fn1">Michael Horton notes, "One cannot conclude that the new perspective represents a cohesive, much less settled, consensus." Michael Horton, <em>Justification, Volume 2</em>, New Studies in Dogmatics, ed. Michael Allen and Scott R. Swain (Grand Rapids, MI: Zondervan Academic, 2018), 25. Regardless of its lack of cohesion, the intellectual movement has led to much discussion around the doctrine of justification, Pauline interpretation, legalism, and what the Jewish community at the time of Christ believed about salvation.[cite: 8] <a class="backref" href="#fnref1">&#8617;</a></li>
          <li id="fn2">The fountainhead of the New Perspective is E. P. Sanders, <em>Paul and Palestinian Judaism</em> (Philadelphia, PA: Fortress Press, 1977). Primary advocates include Sanders, N. T. Wright, and James Dunn.[cite: 8] <a class="backref" href="#fnref2">&#8617;</a></li>
          <li id="fn3">N. T. Wright, <em>What Saint Paul Really Said: Was Paul of Tarsus the Real Founder of Christianity?</em> (Grand Rapids, MI: Eerdmans, 1997), 19, emphasis in the original.[cite: 8] <a class="backref" href="#fnref3">&#8617;</a></li>
          <li id="fn4">Irvin A Busenitz, "The Reformers' Understanding of Paul and the Law," <em>The Master's Seminary Journal</em> 16, no. 2 (2005), 245.[cite: 8] <a class="backref" href="#fnref4">&#8617;</a></li>
          <li id="fn5">For critiques of the New Perspective on Paul, see John Piper, <em>The Future of Justification: A Response to N. T. Wright</em> (Wheaton, IL: Crossway, 2008); Joel Beeke and Paul M. Smalley, <em>Reformed Systematic Theology, Volume 3: Spirit and Salvation</em> (Wheaton, IL: Crossway, 2019), 568-72; and Horton, 20-26, 97-148.[cite: 8] <a class="backref" href="#fnref5">&#8617;</a></li>
          <li id="fn6">There were different sects within the religious community, including the Pharisees, Sadducees, Essenes, and Zealots. A comparison of their distinctives is beyond the scope of this paper. The Gospel writers frequently group the sects together, their members act in unison, and they are condemned collectively by John the Baptist and Jesus. The distinctiveness of the groups (except for the Sadducees and their lack of a belief in the resurrection) is largely ignored by the Gospel writers. While Jews may have recognized unique traits among their religious leaders, the groups as a whole led the people in legalism, ethnocentrism, and a rejection of the Messiah.[cite: 8] <a class="backref" href="#fnref6">&#8617;</a></li>
          <li id="fn7">The Pharisees and Sadducees "coming to his baptism" should not be understood as describing an intent to be baptized for two reasons. First, there is no description of the religious leaders specifically being baptized in any Gospel. Second, Matthew uses ἐπὶ ("to") as a locative in 3:13 when Jesus is baptized. See also Justus A. Freeman, "John the Baptist as a Rejected Prophet in Matthew: The Benefits of Narrative Criticism and Discourse Analysis When Establishing Matthew's Perspective of the Religious Leadership," <em>The Journal of Biblical Pentecostalism</em> 5 (2025): 1-25.[cite: 8] <a class="backref" href="#fnref7">&#8617;</a></li>
          <li id="fn8">Charles L. Quarles, <em>Matthew</em>, ed. T. Desmond Alexander, Thomas R. Schreiner, and Andreas J. Köstenberger, Evangelical Biblical Theology Commentary (Bellingham, WA: Lexham Academic, 2022), 283-84.[cite: 8] <a class="backref" href="#fnref8">&#8617;</a></li>
          <li id="fn9">Donald A. Hagner, <em>Matthew 1-13</em>, vol. 33A, Word Biblical Commentary (Grand Rapids, MI: Zondervan Academic, 2015), 333.[cite: 8] <a class="backref" href="#fnref9">&#8617;</a></li>
          <li id="fn10">Quarles, 236.[cite: 8] <a class="backref" href="#fnref10">&#8617;</a></li>
          <li id="fn11">Steven James Stiles, <em>Jesus' Fulfilment of the Torah and Prophets: Inherited Strategies and Torah Interpretation in Matthew's Gospel</em> (Tübingen: Mohr Siebek, 2023), 147-48, emphasis in the original.[cite: 8] <a class="backref" href="#fnref11">&#8617;</a></li>
          <li id="fn12">Chang Hui Kang, "Justification by Faith in the Gospel of John," <em>ACTS 신학저널</em> 8 (1999), 39.[cite: 8] <a class="backref" href="#fnref12">&#8617;</a></li>
          <li id="fn13">D. A. Carson, <em>The Gospel According to John</em>, The Pillar New Testament Commentary (Grand Rapids, MI: Eerdmans, 1991), 263.[cite: 8] <a class="backref" href="#fnref13">&#8617;</a></li>
          <li id="fn14">Mishnah: Pirkei Avot, 2:7.[cite: 8] <a class="backref" href="#fnref14">&#8617;</a></li>
          <li id="fn15">Colin G. Kruse, <em>John: An Introduction and Commentary</em>, ed. Eckhard J. Schnabel, 2nd ed., Tyndale New Testament Commentaries 4 (London: Inter-Varsity Press, 2017), 179.[cite: 8] <a class="backref" href="#fnref15">&#8617;</a></li>
          <li id="fn16">James M. Hamilton, "John" in, <em>John-Acts</em>, ed. Iain M. Duguid, James M. Hamilton, and Jay Sklar, ESV Expository Commentary 9 (Wheaton, IL: Crossway, 2019), 165.[cite: 8] <a class="backref" href="#fnref16">&#8617;</a></li>
          <li id="fn17">Edward W. Klink, <em>John</em>, ed. Clinton E. Arnold, Zondervan Exegetical Commentary on the New Testament #4 (Grand Rapids, MI: Zondervan Academic, 2016), Chapter 18: John 8:56, eBook Collection (EBSCOhost).[cite: 8] <a class="backref" href="#fnref17">&#8617;</a></li>
          <li id="fn18">Hamilton, 181.[cite: 8] <a class="backref" href="#fnref18">&#8617;</a></li>
          <li id="fn19">Klink, Chapter 19: John 9:41.[cite: 8] <a class="backref" href="#fnref19">&#8617;</a></li>
          <li id="fn20">Kang, 43.[cite: 8] <a class="backref" href="#fnref20">&#8617;</a></li>
          <li id="fn21">Robert H. Stein, <em>Luke</em>, New American Commentary 24 (Nashville, TN: Broadman Press, 1992), 448.[cite: 8] <a class="backref" href="#fnref21">&#8617;</a></li>
          <li id="fn22">Piper, 158. Piper continues, "The Pharisees were committed to establishing their own righteousness, even if they claimed to believe that it was by God's gracious enabling. And the most natural understanding of the meaning of that 'righteousness' is simply obedience to the law with a view to glorifying God. But Jesus said it was only external and therefore hypocritical" (154).[cite: 8] <a class="backref" href="#fnref22">&#8617;</a></li>
          <li id="fn23">F. F. Bruce, "Justification by Faith in the Non-Pauline Writings of the New Testament," <em>The Evangelical Quarterly</em> 24.2 (1952), 66.[cite: 8] <a class="backref" href="#fnref23">&#8617;</a></li>
          <li id="fn24">Beeke and Smalley, 571.[cite: 8] <a class="backref" href="#fnref24">&#8617;</a></li>
          <li id="fn25">Bruce, 67. Bruce further writes, "For where is justifying faith more evident than in the trustful and repentant attitude of mind which, completely divested of self-satisfaction and self-reliance, eagerly seeks and gratefully accepts that pardoning mercy which is the free gift of God's grace?" (67).[cite: 8] <a class="backref" href="#fnref25">&#8617;</a></li>
          <li id="fn26">Yong-Eui Yang, <em>Jesus and the Sabbath in Matthew's Gospel</em>, Library of New Testament Studies (London, UK: T&T Clark, 1997), 145.[cite: 8] <a class="backref" href="#fnref26">&#8617;</a></li>
          <li id="fn27">Piper, 154.[cite: 8] <a class="backref" href="#fnref27">&#8617;</a></li>
          <li id="fn28">C. J. Williams, <em>The Heart of the Matter: Avoiding Legalism</em>, Reformed Presbyterian Theological Journal 1, no. 1 (2014), 37.[cite: 8] <a class="backref" href="#fnref28">&#8617;</a></li>
          <li id="fn29">Quarles, 571.[cite: 8] <a class="backref" href="#fnref29">&#8617;</a></li>
        </ol>
      </div>

      <div class="bibliography">
        <h2>Bibliography</h2>
        <p>Beeke, Joel, and Paul M. Smalley. <em>Reformed Systematic Theology, Volume 3: Spirit and Salvation</em>. Wheaton, IL: Crossway, 2019.[cite: 8]</p>
        <p>Bruce, F. F. "Justification by Faith in the Non-Pauline Writings of the New Testament." <em>The Evangelical Quarterly</em> 24, no. 2 (1952): 66-67.[cite: 8]</p>
        <p>Busenitz, Irvin A. "The Reformers' Understanding of Paul and the Law." <em>The Master's Seminary Journal</em> 16, no. 2 (2005): 245.[cite: 8]</p>
        <p>Carson, D. A. <em>The Gospel According to John</em>. The Pillar New Testament Commentary. Grand Rapids, MI: Eerdmans, 1991.[cite: 8]</p>
        <p>Freeman, Justus A. "John the Baptist as a Rejected Prophet in Matthew: The Benefits of Narrative Criticism and Discourse Analysis When Establishing Matthew's Perspective of the Religious Leadership." <em>The Journal of Biblical Pentecostalism</em> 5 (2025): 1-25.[cite: 8]</p>
        <p>Hagner, Donald A. <em>Matthew 1-13</em>. Vol. 33A. Word Biblical Commentary. Grand Rapids, MI: Zondervan Academic, 2015.[cite: 8]</p>
        <p>Hamilton, James M. "John." In <em>John-Acts</em>. Edited by Iain M. Duguid, James M. Hamilton, and Jay Sklar. ESV Expository Commentary 9. Wheaton, IL: Crossway, 2019.[cite: 8]</p>
        <p>Horton, Michael. <em>Justification, Volume 2</em>. New Studies in Dogmatics. Edited by Michael Allen and Scott R. Swain. Grand Rapids, MI: Zondervan Academic, 2018.[cite: 8]</p>
        <p>Kang, Chang Hui. "Justification by Faith in the Gospel of John." <em>ACTS 신학저널</em> 8 (1999).[cite: 8]</p>
        <p>Klink, Edward W. <em>John</em>. Zondervan Exegetical Commentary on the New Testament #4. Grand Rapids, MI: Zondervan Academic, 2016, eBook Collection (EBSCOhost).[cite: 8]</p>
        <p>Kruse, Colin G. <em>John: An Introduction and Commentary</em>. Edited by Eckhard J. Schnabel. 2nd ed. Tyndale New Testament Commentaries 4. London: Inter-Varsity Press, 2017.[cite: 8]</p>
        <p>Piper, John. <em>The Future of Justification: A Response to N. T. Wright</em>. Wheaton, IL: Crossway, 2008.[cite: 8]</p>
        <p>Quarles, Charles L. <em>Matthew</em>. Edited by T. Desmond Alexander, Thomas R. Schreiner, and Andreas J. Köstenberger. Evangelical Biblical Theology Commentary. Bellingham, WA: Lexham Academic, 2022.[cite: 8]</p>
        <p>Sanders, E. P. <em>Paul and Palestinian Judaism</em>. Philadelphia, PA: Fortress Press, 1977.[cite: 8]</p>
        <p>Stein, Robert H. <em>Luke</em>. New American Commentary 24. Nashville, TN: Broadman Press, 1992.[cite: 8]</p>
        <p>Stiles, Steven James. <em>Jesus' Fulfilment of the Torah and Prophets: Inherited Strategies and Torah Interpretation in Matthew's Gospel</em>. Tübingen: Mohr Siebek, 2023.[cite: 8]</p>
        <p>Williams, C. J. <em>The Heart of the Matter: Avoiding Legalism</em>. Reformed Presbyterian Theological Journal 1, no. 1 (2014).[cite: 8]</p>
        <p>Wright, N. T. <em>What Saint Paul Really Said: Was Paul of Tarsus the Real Founder of Christianity?</em> Grand Rapids, MI: Eerdmans, 1997.[cite: 8]</p>
        <p>Yang, Yong-Eui. <em>Jesus and the Sabbath in Matthew's Gospel</em>. Library of New Testament Studies. London, UK: T&T Clark, 1997.[cite: 8]</p>
      </div>
    `
  }
];
